language: python
python:
  - "3.4"
# command to install dependencies and launch web server
install:
  - pip install -r requirements.txt
  - ./app.py &
  - sleep 5
# command to run tests
script:
  - pyresttest http://localhost:5000 tests/quick_suite.yaml
